### ISSUE TITLE
3.6.5: Lambdaレイヤー登録時のエラー

### ISSUE THREAD

**Issue by miyamoto-iwaki** [minorun365/bedrock-book#42]
Cloud9が停止され、Streamlitで進めている者です。本書で指定されたPythonライブラリのみを取得し、botoを削除しています。しかし、langchain-layer.zipの容量が72.46MBとなってしまい、Lambdaレイヤーに登録するコマンドを実行すると以下のエラーが出て解決できません。対処方法を教えていただけますと幸いです。
`An error occurred (RequestEntityTooLargeException) when calling the PublishLayerVersion operation: Request must be smaller than 70167211 bytes for the PublishLayerVersion operation`

**Comment by moritalous** [comment]
ご質問ありがとうございます。
以下の手順で試したところ、Lambdaレイヤーのアップロードが正しく行えました。
実施いただいた手順と違いはありますでしょうか？

## 環境

以下のブログで解説している「SageMaker Studio コードエディタ」環境を使用します。

[AWS Cloud9が突然、新規利用不可に？ 代替策「SageMaker Studio コードエディタ」の利用手順
](https://qiita.com/minorun365/items/f5289163795d5d7b21e2)

手順に沿って実行してください。

* IAMロールへの権限追加

    AWSLambda_FullAccess権限を付与してください。

* Pythonバージョン

    ```python
    conda init
    conda create -n handson python=3.9.16 --yes
    
    echo "conda activate handson" >> ~/.bashrc
    
    source ~/.bashrc 
    ```

* 追加でインストールが必要なソフトウェア

    ```python
    sudo apt install -y zip
    ```

のあたりはLambdaレイヤーを作成にあたって影響すると思います。

## Lambdaレイヤー作成手順

```python
mkdir python
pip install -t python langchain==0.2.0 langchain-aws==0.1.4 langchain-community==0.2.0 python-dateutil==2.8.2

rm -r python/boto*

zip -r9 langchain-layer.zip python

aws lambda publish-layer-version \
--layer-name langchain-layer \
--compatible-runtimes python3.9 \
--compatible-architectures x86_64 \
--zip-file fileb://langchain-layer.zip --no-cli-pager

```

---

一点気になったこととしては、上記手順を実施した際、zipファイルのサイズが50MB未満でしたので72.46MBですと、不要なものが含まれているかもしれません。

```shell
ls -la langchain-layer.zip 
```
```
-rw-r--r-- 1 sagemaker-user users 46326080 Oct 27 11:33 langchain-layer.zip
```


ご確認よろしくお願いいたします。
